### ISSUE TITLE
WanBot doesn't work in threads

### ISSUE THREAD

**Issue by iethree** [iethree/wan-party-bot#3]
- [x] make it work in threads

**Comment by stmhull** [comment]
https://stackoverflow.com/questions/70476875/is-there-a-way-to-create-a-thread-in-discord-py#:~:text=The%20current%20version%20of%20discord,beta%20and%20is%20much%20better.

**Comment by justinbarak** [comment]
> https://stackoverflow.com/questions/70476875/is-there-a-way-to-create-a-thread-in-discord-py#:~:text=The%20current%20version%20of%20discord,beta%20and%20is%20much%20better.

Great reference, think it's worth waiting for the discord 2.0 version?

**Comment by stmhull** [comment]
Great work team
